name: CI (build + test)

on: [push]

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout du code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      # 3. Installation des dépendances
      - name: Install dependencies
        run: npm ci

      # 4. Build de l’application Next.js
      - name: Build Next.js app
        run: npm run build



      # 5. Lancement des tests (avec enregistrement vidéo)
      #    → On suppose que votre script de tests (ex. Playwright/Cypress) génère une vidéo dans un dossier connu, 
      #      par exemple "./tests/videos"
      - name: Run tests (génération de la vidéo)
        run: npm run e2e headless
        # ↳ Votre npm test doit être configuré pour enregistrer la vidéo de la session de test, 
        #   par exemple dans tests/videos/*.mp4



      # 6. Upload de la ou des vidéo(s) de test en tant qu’artifact
      - name: Upload test video(s) as artifact
        if: always()   # même si certains tests échouent, on souhaite récupérer la vidéo
        uses: actions/upload-artifact@v4
        with:
          name: test-videos
          path: tests/videos/*.mp4
